export const LANGUAGES = {
  typescript: "5.0.3",
  javascript: "18.15.0",
  c: "10.2.0",
  "c++": "10.2.0",
  go: "1.16.2",
  java: "15.0.2",
  kotlin: "1.8.20",
  csharp: "6.12.0",
  php: "8.2.3",
  python2: "2.7.18",
  python: "3.10.0",
  ruby: "3.0.1",
  rust: "1.68.2",
  sqlite3: "3.36.0",
  swift: "5.3.3",
};

export const CODE_SNIPPETS = {
  javascript: `\nfunction greet(name) {\n\tconsole.log("Hello, " + name + "!");\n}\n\ngreet("Ruhul");\n`,
  typescript: `\ntype Params = {\n\tname: string;\n}\n\nfunction greet(data: Params) {\n\tconsole.log("Hello, " + data.name + "!");\n}\n\ngreet({ name: "Ruhul" });\n`,
  c: `\n#include <stdio.h>\n\nint main() {\n\tprintf("Hello, Ruhul!\\n");\n\treturn 0;\n}\n`,
  "c++": `\n#include <iostream>\n\nint main() {\n\tstd::cout << "Hello, Ruhul!" << std::endl;\n\treturn 0;\n}\n`,
  go: `\npackage main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("Hello, Ruhul!")\n}\n`,
  java: `\npublic class HelloWorld {\n\tpublic static void main(String[] args) {\n\t\tSystem.out.println("Hello, Ruhul!");\n\t}\n}\n`,
  kotlin: `\nfun main() {\n\tprintln("Hello, Ruhul!")\n}\n`,
  csharp: `\nusing System;\n\nnamespace HelloWorld {\n\tclass Hello {\n\t\tstatic void Main(string[] args) {\n\t\t\tConsole.WriteLine("Hello, Ruhul!");\n\t\t}\n\t}\n}\n`,
  php: `\n<?php\n\n$name = 'Ruhul';\necho "Hello, $name!";\n?>\n`,
  python2: `\ndef greet(name):\n\tprint "Hello, " + name + "!"\n\ngreet("Ruhul")\n`,
  python: `\ndef greet(name):\n\tprint("Hello, " + name + "!")\n\ngreet("Ruhul")\n`,
  ruby: `\ndef greet(name)\n\tputs "Hello, #{name}!"\nend\n\ngreet("Ruhul")\n`,
  rust: `\nfn main() {\n\tprintln!("Hello, Ruhul!");\n}\n`,
  sqlite3: `\nCREATE TABLE greeting (\n\tname TEXT\n);\n\nINSERT INTO greeting (name) VALUES ('Ruhul');\n\nSELECT 'Hello, ' || name || '!' FROM greeting;\n`,
  swift: `\nimport Foundation\n\nlet name = "Ruhul"\nprint("Hello, \\(name)!")\n`,
};
